trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infrastructure/environment/**
      - infrastructure/deploy.yml

parameters:
  - name: environment
    type: string
    default: 'dev'
    values:
      - dev
      - prod

variables:
  ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    varFile: 'dev.tfvars'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    varFile: 'prod.tfvars'

extends:
  template: deploy.yml
  parameters:
    workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure/environment'
    backendAzureRmKey: 'infra.tfstate'
    commandOptions: '-var="service_principal_id=$(SERVICE_PRINCIPAL_ID)" -var-file="${{ variables.varFile }}"' 