trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infrastructure/capability/**
      - infrastructure/deploy.yml

parameters:
  - name: workingDirectory
    type: string
    default: '$(System.DefaultWorkingDirectory)/infrastructure/capability'

extends:
  template: deploy.yml
  parameters:
    workingDirectory: ${{ parameters.workingDirectory }}
    backendAzureRmKey: 'capability.tfstate'
    commandOptions: '-var="service_principal_id=$(SERVICE_PRINCIPAL_ID)"' 