trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infrastructure/capability/**
      - infrastructure/deploy.yml

stages:
- stage: Deploy_Capability_Infrastructure
  displayName: 'Deploy Capability Infrastructure'
  jobs:
  - template: deploy.yml
    parameters:
      jobDisplayName: 'Terraform Deploy Capability'
      workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure/capability'
      backendAzureRmKey: 'capability.tfstate'
      commandOptions: '-var="service_principal_id=$(SERVICE_PRINCIPAL_ID)" -var="admin_object_id=$(AdminAccountObjectID)"' 