parameters:
- name: workingDirectory
  type: string
  default: ''
- name: stateKey
  type: string
  default: ''
- name: varFile
  type: string
  default: ''

jobs:
- job: Deploy
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureCLI@2
    displayName: 'Azure Login'
    inputs:
      azureSubscription: 'Azure Subscription'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Show account info for debugging
        echo "Debug: Account info:"
        az account show
        
        # Get subscription ID
        echo "Debug: Getting subscription ID..."
        SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        echo "Debug: Subscription ID: $SUBSCRIPTION_ID"
        echo "##vso[task.setvariable variable=SUBSCRIPTION_ID]$SUBSCRIPTION_ID"

  - task: TerraformInstaller@1
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTaskV4@4
    displayName: 'Terraform Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: ${{ parameters.workingDirectory }}
      backendServiceArm: 'Azure Subscription'
      backendAzureRmResourceGroupName: 'wedding-api-capability-rg'
      backendAzureRmStorageAccountName: 'weddingapistate'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: ${{ parameters.stateKey }}

  - task: TerraformTaskV4@4
    displayName: 'Import Resource Group'
    inputs:
      provider: 'azurerm'
      command: 'import'
      workingDirectory: ${{ parameters.workingDirectory }}
      environmentServiceNameAzureRM: 'Azure Subscription'
      resourceAddress: 'azurerm_resource_group.wedding_api_capability_rg'
      resourceId: '/subscriptions/$(SUBSCRIPTION_ID)/resourceGroups/wedding-api-capability-rg'
    continueOnError: true

  - task: TerraformTaskV4@4
    displayName: 'Import Storage Account'
    inputs:
      provider: 'azurerm'
      command: 'import'
      workingDirectory: ${{ parameters.workingDirectory }}
      environmentServiceNameAzureRM: 'Azure Subscription'
      resourceAddress: 'azurerm_storage_account.terraform_state'
      resourceId: '/subscriptions/$(SUBSCRIPTION_ID)/resourceGroups/wedding-api-capability-rg/providers/Microsoft.Storage/storageAccounts/weddingapistate'
    continueOnError: true

  - task: TerraformTaskV4@4
    displayName: 'Import Storage Container'
    inputs:
      provider: 'azurerm'
      command: 'import'
      workingDirectory: ${{ parameters.workingDirectory }}
      environmentServiceNameAzureRM: 'Azure Subscription'
      resourceAddress: 'azurerm_storage_container.terraform_state'
      resourceId: 'https://weddingapistate.blob.core.windows.net/tfstate'
    continueOnError: true

  - task: TerraformTaskV4@4
    displayName: 'Terraform Plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: ${{ parameters.workingDirectory }}
      environmentServiceNameAzureRM: 'Azure Subscription'
      commandOptions: ${{ parameters.varFile }}

  - task: TerraformTaskV4@4
    displayName: 'Terraform Apply'
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: ${{ parameters.workingDirectory }}
      environmentServiceNameAzureRM: 'Azure Subscription'
      commandOptions: ${{ parameters.varFile }} 