trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infrastructure/environment/**
      - infrastructure/deploy.yml

stages:
- stage: Deploy_Dev_Environment
  displayName: 'Deploy Dev Environment'
  jobs:
  - template: deploy.yml
    parameters:
      jobDisplayName: 'Terraform Deploy Dev'
      workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure/environment'
      backendAzureRmKey: 'environment-dev.tfstate'
      commandOptions: '-var="service_principal_id=$(SERVICE_PRINCIPAL_ID)" -var-file="dev.tfvars"'

- stage: Deploy_Prod_Environment
  displayName: 'Deploy Prod Environment'
  dependsOn: Deploy_Dev_Environment
  condition: succeeded()
  jobs:
  - template: deploy.yml
    parameters:
      jobDisplayName: 'Terraform Deploy Prod'
      workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure/environment'
      backendAzureRmKey: 'environment-prod.tfstate'
      commandOptions: '-var="service_principal_id=$(SERVICE_PRINCIPAL_ID)" -var-file="prod.tfvars"' 