trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - infrastructure/environment/**
      - infrastructure/deploy.yml

parameters:
  - name: environment
    type: string
    default: 'dev'
    values:
      - dev
      - prod
  - name: workingDirectory
    type: string
    default: '$(System.DefaultWorkingDirectory)/infrastructure/environment'

${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
  extends:
    template: deploy.yml
    parameters:
      workingDirectory: ${{ parameters.workingDirectory }}
      backendAzureRmKey: 'environment-dev.tfstate'
      commandOptions: '-var="service_principal_id=$(SERVICE_PRINCIPAL_ID)" -var-file="dev.tfvars"'

${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
  extends:
    template: deploy.yml
    parameters:
      workingDirectory: ${{ parameters.workingDirectory }}
      backendAzureRmKey: 'environment-prod.tfstate'
      commandOptions: '-var="service_principal_id=$(SERVICE_PRINCIPAL_ID)" -var-file="prod.tfvars"' 