trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - infrastructure/environment/**

parameters:
  - name: environment
    type: string
    default: 'dev'
    values:
      - dev
      - prod

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DeployDev
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  jobs:
  - deployment: DeployDevEnvironment
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - template: deploy.yml
            parameters:
              workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure/environment'
              stateKey: 'environment-dev.tfstate'
              varFile: '-var-file="dev.tfvars"'

- stage: DeployProd
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: DeployProdEnvironment
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - template: deploy.yml
            parameters:
              workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure/environment'
              stateKey: 'environment-prod.tfstate'
              varFile: '-var-file="prod.tfvars"' 